### ISSUE TITLE
Crash if ipv6 DNS server configured in system

### ISSUE THREAD

**Issue by zhovner** [SpiderLabs/Responder#90]
`Traceback (most recent call last):
  File "Responder.py", line 257, in <module>
    main()
  File "Responder.py", line 180, in main
    from poisoners.LLMNR import LLMNR
  File "/usr/share/responder/poisoners/LLMNR.py", line 57, in <module>
    IsICMPRedirectPlausible(settings.Config.Bind_To)
  File "/usr/share/responder/poisoners/LLMNR.py", line 49, in IsICMPRedirectPlausible
    if x !="127.0.0.1" and IsOnTheSameSubnet(x,IP) == False:
  File "/usr/share/responder/poisoners/LLMNR.py", line 34, in IsOnTheSameSubnet
    ipaddr = int(''.join([ '%02x' % int(x) for x in ip.split('.') ]), 16)
ValueError: invalid literal for int() with base 10: 'fdd1:232b:380c::1'
`

**Comment by lgandx** [comment]
Thanks for your report. Unfortunately Responder has no support for IPv6.

**Comment by Jake3231** [comment]
@zhovner are you using macOS? If so, I found a way to get around this issue.

**Comment by zhovner** [comment]
@Jake3231 yes, i'm using macOS 10.13.3. What the solution?

**Comment by Jake3231** [comment]
It turns out that in the network preferences in System Preferences, you can sort of disable IPv6.

1. Open System Preferences and select the interface you are using in the left sidebar. From there, you may need to unlock the preference pane by clicking the padlock in the bottom left corner of the window.
2. Select `Advanced` and navigate to the `TCP/IP` tab in the sheet that drops down.
3. Next to `Configure IPv6:` there will be a drop down in which `Automatically` will be selected by default. Change that to `Link-local only`. Now the error should not occur.

**Comment by zhovner** [comment]
Thank you, but this is not a solution for me. I can remove ipv6 from the system but I really need it and use it.

**Comment by Jake3231** [comment]
Okay. I'm now aware of any other solution, unfortunately. If you are able to work without IPv6, this will at least allow Responder to work. If I find a way to make this work without disabling IPv6, I will let you know.

**Comment by videoman** [comment]
You could also try using the current version of responder here: https://github.com/lgandx/Responder no updates to this project have been made in a long time.
